apiVersion: v1
kind: Service
metadata:
  name: app-status-service
spec:
  selector:
    app: status
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31300
  type: LoadBalancer
